### ISSUE TITLE
Unexpected Character Issue

### ISSUE THREAD

**Issue by evanshortiss** [yaronn/xpath.js#8]
I've been trying to parse an XML document but continually get unexpected character issues.

First I _Error: Unexpected character ?_ due to the first line:

```
<?xml version="1.0" encoding="utf-8"?>
```

When I remove it I get _"Error: Unexpected character !"_ due to a comment in the document.

After removing comments I get _"Error: Unexpected character :"_. Many colon characters exist both in XML attributes and the data in my document. 

This is happening with the latest version and 0.0.4. I haven't tested other versions. Using [this](https://github.com/goto100/xpath) module gets around the problem, but I'm not sure of the differences.

**Comment by andreafresa** [comment]
Hello guys, I am having similar issue. 
My xpath statement is this one (I added an xml namespace ,ns1):
`
var Objects = select("//ns1:References/ns1:Reference[@ReferenceType="+typeofref+"]/text()="+id.toString(), ns);
`
But the id that I am passing is this one: ns=2;i=16601

The error that i get is this one (I suppose it is because I am passing a string with a ; inside):
`
throw new Error("Unexpected character " + c);
Error: Unexpected character ;
`

Is it a bug? How can I solve the issue?
Thanks
